### ISSUE TITLE
How do we pass in the release notes?

### ISSUE THREAD

**Issue by brandtdaniels** [bitrise-steplib/steps-deploy-to-itunesconnect-application-loader#18]
How do we pass in the release notes?

**Comment by bitce** [comment]
Hi @brandtdaniels!

You can't pass release notes using this step, you should be looking for: https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver

The step has an input field, called “options” (https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/blob/master/step.yml#L172). With this you can pass extra data to the deliver command!

**Comment by brandtdaniels** [comment]
The reason I picked this step over the other one is because it uses the TestFlight logo. The other one seemed geared more toward releasing to the public.

**Comment by bitce** [comment]
In essence, both do the same thing. The one I'm referring to has the option you seem to be specifically looking for.
