### ISSUE TITLE
Deploy to iTunes Connect - Application Loader fails with "Input error: neither ipa_path nor pkg_path is provided"

### ISSUE THREAD

**Issue by gitrago** [bitrise-steplib/steps-deploy-to-itunesconnect-application-loader#21]
I have the step "**Deploy to iTunes Connect - Application Loader**" right after the step "**Xcode Archive & Export for iOS**" and I expected the latter would set the variable "$BITRISE_IPA_PATH" properly.
It does not seem to be the case: Step "**Deploy to iTunes Connect - Application Loader**" errors out with message `Input error: neither ipa_path nor pkg_path is provided`

Input variable 'IPA path' is set to `$BITRISE_IPA_PATH`

Please help, thank you.

**Comment by bitce** [comment]
Hi @gitrago  can you please include an URL to a build where this happens?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @gitrago  please let us know if we can help with anything by opening a new issue!
