### ISSUE TITLE
Use App Store Connect API credentials configured on Bitrise account

### ISSUE THREAD

**Issue by copini** [bitrise-steplib/steps-deploy-to-itunesconnect-application-loader#24]
Now that it's possible to configure App Store Connect API credentials in your Bitrise account settings (https://blog.bitrise.io/app-store-connect-api-on-bitrise), it seems to make sense for this step to (optionally?) use the same credentials.

Are there any plans to implement this? Or is there perhaps some way the URL of the key uploaded to your account and the configured Issuer ID can already be used (exposed as environment variables?) in this step?

The only way to do it now, as far as I can see, is to upload the same .p8 file to Generic File Storage and provide the URL and Issuer ID in the input variables of this step. That seems redundant and feels less secure.

**Comment by godrei** [comment]
Hi @copini , sorry for the late response!
We added support for Bitrise Apple Service connection in version [1.0.0](https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-application-loader/releases/tag/1.0.0).

I'll close this issue, but if you need more info/help just open a new one!
