### ISSUE TITLE
Wrong email during authorization 

### ISSUE THREAD

**Issue by mkkroliks** [bitrise-steplib/steps-deploy-to-itunesconnect-application-loader#45]
### Troubleshooting

- [✅ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.4.0
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I try to authenticate using apple_id and app_specific_password, but xcrun altool uses wrong email, that is not specified in secrets.  I know that API Key authentication has priority over Apple ID authorization, but my account is not configured for API Key authorization

### Bitrise info

<img width="1003" alt="Screen Shot 2022-03-17 at 15 41 56" src="https://user-images.githubusercontent.com/2151961/158832035-117dca05-e67c-4a6d-bdc4-a35cb24d4fea.png">
<img width="1365" alt="Screen Shot 2022-03-17 at 15 40 55" src="https://user-images.githubusercontent.com/2151961/158832043-198433ae-484e-4100-8c56-604039dd70de.png">

<details>
  <pre>
Bitrise Apple Developer Connection with Apple ID found.
Uploading - AAFP.ipa ...
$ xcrun "altool" "--upload-app" "-f" "/Users/vagrant/deploy/AAFP.ipa" "--type" "ios" "--username" "wrongEmail@me.com" "--password" "[REDACTED]"
*** Error: Error uploading '/Users/vagrant/deploy/AAFP.ipa'.
*** Error: Unable to upload archive. Failed to get authorization for username 'wrongEmail@me.com' and password. (
    "Error Domain=ITunesConnectionOperationErrorDomain Code=-19000 \"Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com\" UserInfo={NSLocalizedRecoverySuggestion=Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com, NSLocalizedDescription=Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com, NSLocalizedFailureReason=App Store operation failed.}"
) (-1011)
 {
    NSLocalizedDescription = "Unable to upload archive.";
    NSLocalizedFailureReason = "Failed to get authorization for username 'wrongEmail@me.com' and password. (\n    \"Error Domain=ITunesConnectionOperationErrorDomain Code=-19000 \\\"Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com\\\" UserInfo={NSLocalizedRecoverySuggestion=Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com, NSLocalizedDescription=Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com, NSLocalizedFailureReason=App Store operation failed.}\"\n)";
}
Uploading IPA failed: exit status 1
  </pre>
</details>

**Comment by shams-ahmed** [comment]
Hi @mkkroliks can send the build URL or send support a message with the details so we can look into it?

I would suggest looking a this [page](https://app.bitrise.io/me/profile#/apple_developer_account) and checking out all of your environment variables using `printenv` in a script step

**Comment by mkkroliks** [comment]
Hi @shams-ahmed here Is a link to build: https://app.bitrise.io/build/1ed626a3-a8dd-4536-96b5-19b24688d87b#?tab=log
I don't have any environment variables added under a link you sent. 
<img width="840" alt="Screen Shot 2022-03-18 at 09 13 55" src="https://user-images.githubusercontent.com/2151961/158962250-18b57146-ff3d-4abd-bf86-f6b3ddb62c3f.png">

**Comment by shams-ahmed** [comment]
@mkkroliks can you please [enable support?](https://devcenter.bitrise.io/en/apps/enabling-the-bitrise-support-user-for-your-app.html)

**Comment by mkkroliks** [comment]
@shams-ahmed ✅

**Comment by shams-ahmed** [comment]
@mkkroliks you have two options:
- set connection to `off`. this should enforce the use of custom apple id and password
- create an apple id connection under your profile setting - > apple service connection. afterwards update your project connection type here: https://app.bitrise.io/app/f66b7caea6542b4d#/team

**Comment by mkkroliks** [comment]
@shams-ahmed Thank you for your help!
